import { contextBridge, ipcRenderer } from "electron";

// Único puente entre la interfaz (sin acceso a Node) y el proceso principal.
contextBridge.exposeInMainWorld("discalaves", {
  // Windows: primer arranque (WSL). En Linux, wslEstado responde "no-aplica".
  wslEstado: () => ipcRenderer.invoke("wsl:estado"),
  wslActivar: () => ipcRenderer.invoke("wsl:activar"),
  wslPreparar: () => ipcRenderer.invoke("wsl:preparar"),
  instalarEstado: () => ipcRenderer.invoke("instalar:estado"),
  instalarEjecutar: () => ipcRenderer.invoke("instalar:ejecutar"),
  alProgresoWsl: (f: (texto: string) => void) => ipcRenderer.on("wsl:progreso", (_e, texto) => f(texto)),
  conversaciones: () => ipcRenderer.invoke("conversaciones"),
  modelos: () => ipcRenderer.invoke("modelos"),
  plantillas: () => ipcRenderer.invoke("plantillas"),
  empleado: (id: string) => ipcRenderer.invoke("empleado", id),
  crearEmpleado: (datos: unknown, plantilla?: string) => ipcRenderer.invoke("crear-empleado", datos, plantilla),
  guardarEmpleado: (id: string, datos: unknown) => ipcRenderer.invoke("guardar-empleado", id, datos),
  borradorEmpleado: (descripcion: string) => ipcRenderer.invoke("borrador-empleado", descripcion),
  abrirCarpeta: (id: string) => ipcRenderer.invoke("abrir-carpeta", id),
  historial: (id: string) => ipcRenderer.invoke("historial", id),
  estado: (id: string) => ipcRenderer.invoke("estado", id),
  enviar: (id: string, texto: string) => ipcRenderer.invoke("enviar", id, texto),
  detener: (id: string) => ipcRenderer.invoke("detener", id),
  aprobar: (id: string, si: boolean) => ipcRenderer.invoke("aprobar", id, si),
  verPantalla: (id: string, ver: boolean) => ipcRenderer.invoke("pantalla:ver", id, ver),
  controlPantalla: (id: string, activo: boolean) => ipcRenderer.invoke("pantalla:control", id, activo),
  modoLibre: (id: string, activo: boolean) => ipcRenderer.invoke("modo-libre", id, activo),
  // Proveedores fuera de este equipo: la interfaz nunca recibe las claves guardadas.
  proveedores: () => ipcRenderer.invoke("proveedores"),
  guardarProveedor: (datos: unknown) => ipcRenderer.invoke("guardar-proveedor", datos),
  borrarProveedor: (id: string) => ipcRenderer.invoke("borrar-proveedor", id),
  probarProveedor: (id: string) => ipcRenderer.invoke("probar-proveedor", id),
  codexSesion: () => ipcRenderer.invoke("codex-sesion"),
  alPreguntaSsh: (f: (p: unknown) => void) => ipcRenderer.on("ssh:pregunta", (_e, p) => f(p)),
  responderSsh: (id: string, valor: string | null) => ipcRenderer.invoke("ssh:respuesta", id, valor),
  alCambiarEstado: (f: (estado: unknown) => void) => ipcRenderer.on("estado", (_e, estado) => f(estado)),
  alRecibirTrozo: (f: (trozo: unknown) => void) => ipcRenderer.on("trozo", (_e, trozo) => f(trozo)),
  alPaso: (f: (id: string) => void) => ipcRenderer.on("paso", (_e, id) => f(id)),
  alAprobacion: (f: (p: unknown) => void) => ipcRenderer.on("aprobacion", (_e, p) => f(p)),
  alEquipo: (f: (activos: string[]) => void) => ipcRenderer.on("equipo", (_e, activos) => f(activos)),
});
